# Generated by Django 2.2.3 on 2019-07-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20190715_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('8:45 - 9:45', '8:45 - 9:45'), ('9:45 - 10:45', '9:45 - 10:45'), ('10:45 - 11:45', '10:45 - 11:45'), ('12:30 - 1:30', '12:30 - 1:30'), ('1:30 - 2:30', '1:30 - 2:30'), ('2:30 - 3:30', '2:40 - 3:30')], default='11:45 - 12:30', max_length=50),
        ),
    ]
